### ISSUE TITLE
Create a DB/Users list instead of creating and admin user

### ISSUE THREAD

**Issue by francois09** [francois09/ansible_role_database#1]
With a format like:
```
database__create:
  - db_name: database
    db_user: username
    db_pass: password
...
```
